### ISSUE TITLE
unconfigured plug-in brings down service

### ISSUE THREAD

**Issue by pejvan** [gocd-contrib/gocd-oauth-login#3]
If for some reason, you end up enabling authentication while not having configured the plug-in, the plug-in throws an exception which in turn brings down the entire server with a server "render error".

plugin-google.oauth.login.log

```
2015-07-16 21:21:31,780 ERROR [qtp109961541-30] OAuthLoginPlugin:77 - Error occurred while OAuth setup.
java.lang.RuntimeException: plugin is not configured. please provide plugin settings.
```

go-server.log 

```
2015-07-16 21:21:31,786  WARN [qtp109961541-30] ServletHandler:620 - 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: render error page
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
```

**Comment by srinivasupadhya** [comment]
> brings down the entire server

you mean the server does not respond to other requests anymore? and yes, you need to configure it before starting to use it.

**Comment by pejvan** [comment]
Indeed, the server doesn't respond after that.
