### ISSUE TITLE
GitHub organization authentication

### ISSUE THREAD

**Issue by mnbittorrent** [gocd-contrib/gocd-oauth-login#36]
I'm having some trouble piecing together what it takes to authenticate by GitHub organization. The only thing that is clear is how to setup an OAuth client ID and secret.

How should I fill out these:

| Setting | Value |
| --- | --- |
| Server Base URL | Already documented. |
| OAuth Client ID | Already documented. |
| OAuth Client Secret | Already documented. |
| Username | Why would you need a user? |
| Password | Isn't the whole point of oauth to not need a user/password? |
| OAuth Token | Already documented. |
| Username Regular Expression | **Presumably this is where you filter for your organization. What's an example look like? Is it just the organization name?** |

Thanks!

**Comment by macdiesel** [comment]
@mnbittorrent I too am having the same issue figuring out how to configure oauth with github using go-server 16.1.0-2855. Have you had any additional luck with this? 

Here is the stack trace that I am receiving when attempting to search for users after configuring the plugin: 
2016-02-17 20:36:48,315  WARN [qtp210010063-26] GitHubProvider:67 - Error occurred while trying to perform user search
java.lang.RuntimeException: Plugin not configured. Please provide plugin settings.
        at com.tw.go.plugin.provider.github.GitHubProvider.getGitHub(GitHubProvider.java:116)
        at com.tw.go.plugin.provider.github.GitHubProvider.searchUser(GitHubProvider.java:65)
        at com.tw.go.plugin.OAuthLoginPlugin.handleSearchUserRequest(OAuthLoginPlugin.java:192)
        at com.tw.go.plugin.OAuthLoginPlugin.handle(OAuthLoginPlugin.java:97)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        at com.thoughtworks.go.plugin.access.authentication.AuthenticationExtension.searchUser(AuthenticationExtension.java:78)
        at com.thoughtworks.go.server.security.UserSearchService.searchUsingPlugins(UserSearchService.java:115)
        at com.thoughtworks.go.server.security.UserSearchService.search(UserSearchService.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by mnbittorrent** [comment]
I ended up creating a [github access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) to fix this problem. This step is missing in the setup instructions, but it is required.

I could never figure out what to do with username regular expression, so I configured Go to filter users with `allowOnlyKnownUsersToLogin`. This works okay for my small team, but it would be much easier to be able to filter based on github organization for larger teams.

```
<security allowOnlyKnownUsersToLogin="true">
  <roles>
    <role name="dev">
      <users>
        <user>user1</user>
        <user>user2</user>
        <user>user3</user>
        <user>user4</user>
      </users>
    </role>
  </roles>
  <admins>
    <user>user1</user>
  </admins>
</security>
```

**Comment by swarren83** [comment]
Without the ability to filter users, anyone with a github account can log in to GoCD with this plugin configured.  This is less than ideal for real world use.

@ketan Would you be able to provide more details around the "Username Regular Expression" field?

**Comment by arvindsv** [comment]
Taking a quick look at the code [for GitHub](https://github.com/gocd-contrib/gocd-oauth-login/blob/7e219deb0915b036d850608f6fb8ed3dab83ddc2/src/main/java/com/tw/go/plugin/provider/github/GitHubProvider.java#L84-L106) and [for Google](https://github.com/gocd-contrib/gocd-oauth-login/blob/7e219deb0915b036d850608f6fb8ed3dab83ddc2/src/main/java/com/tw/go/plugin/provider/google/GoogleProvider.java#L59-L61), it seems to be like this (completely untested. So, if it works, please submit a PR to update documentation):
1. Google:
   - It looks like the "Username regex" in the plugin settings page is checked against the username of the user who's trying to log in. So, something like `.*@yourcompany.com$` _should_ allow only users with domain "@yourcompany.com" to log in.
2. GitHub:
   - It looks like having an empty "Username regex" field in the plugin settings page allows anyone with a valid GitHub account to log in.
   - If the regex is not empty, then the "Username regex" field is used as an organization regex instead. So, a value of "gocd" in it _should_ allow only users belonging to the "gocd" organization to log in.

Again, this is untested, but since you have setups where this is happening, please try it, correct it if needed and submit a PR to update the README to help others.

Thanks!

**Comment by arvindsv** [comment]
@mnbittorrent: From [this code](https://github.com/gocd-contrib/gocd-oauth-login/blob/7e219deb0915b036d850608f6fb8ed3dab83ddc2/src/main/java/com/tw/go/plugin/provider/github/GitHubProvider.java#L110-L114), it looks like the username and password are an option. If you provide the username and password, then it uses that to connect. If not, it uses the OAuth token to connect.

The settings UI of this plugin should be made much better, imho.

**Comment by tonyzwei** [comment]
I think I got the fix eventually. In setting window of Google OAuth Login, give the value of .*@mycompany.com$ to Username Regular Expression, instead of Username.
allowOnlyKnownUsersToLogin="true" only works for users who have already signed up.

**Comment by betarelease** [comment]
I tried with your suggestion @arvindsv for my Github organization. When I add the organization name in  Username regex field and try to authenticate with my github OAuth, it fails authentication.

**Comment by ketan** [comment]
There is a new [2.0 release](https://github.com/gocd-contrib/gocd-oauth-login/releases/tag/v2.0) that addresses all the issues highlighted here.

Please be sure re-configure the plugins again, after you install them.
